/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;

/**
 *
 * @author ENTRAPTA
 */
public class XableirosRepoAssistente extends javax.swing.JFrame {

    /**
     * Creates new form XableirosRepoAssistente
     */
    public XableirosRepoAssistente() {
        initComponents();
        assistenteJanela = new AssistenteJanela(this);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataBaseTypeButtonGroup = new javax.swing.ButtonGroup();
        BackGroundPanel = new javax.swing.JPanel();
        TittleLabe = new javax.swing.JLabel();
        FooterLabel = new javax.swing.JLabel();
        tellYouLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        rightTabbedPane = new javax.swing.JTabbedPane();
        dsTabPanel = new javax.swing.JPanel();
        readDsButton = new javax.swing.JButton();
        replaceDsButton = new javax.swing.JButton();
        dsPathScrollPanel = new javax.swing.JScrollPane();
        dsPathList = new javax.swing.JList<>();
        viewButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        saveAsButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        comumCheckBox = new javax.swing.JCheckBox();
        contratoCheckBox = new javax.swing.JCheckBox();
        patrimonioCheckBox = new javax.swing.JCheckBox();
        copyDsLabel = new javax.swing.JLabel();
        scriptsTabPanel = new javax.swing.JPanel();
        idDoContratoText = new javax.swing.JTextField();
        idDoContratoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        repoTabPanel = new javax.swing.JPanel();
        configTabPanel = new javax.swing.JPanel();
        pathDsLabel = new javax.swing.JLabel();
        pathDsText = new javax.swing.JTextField();
        pathDeployText = new javax.swing.JTextField();
        pathDeployLabel = new javax.swing.JLabel();
        saveConfigFile = new javax.swing.JButton();
        backGroundColorLabel = new javax.swing.JLabel();
        backGroundColorText = new javax.swing.JTextField();
        foreGroundColorLabel = new javax.swing.JLabel();
        foreGroundColorText = new javax.swing.JTextField();
        FooterLabel1 = new javax.swing.JLabel();
        leftTabbedPanel = new javax.swing.JTabbedPane();
        firstTabTablePanel = new javax.swing.JPanel();
        textArea01ScrollPane2 = new javax.swing.JScrollPane();
        panel01TextArea = new javax.swing.JTextArea();
        secondTabTablePanel = new javax.swing.JPanel();
        textArea02ScrollPane = new javax.swing.JScrollPane();
        panel02TextArea = new javax.swing.JTextArea();
        thirdTabTablePanel = new javax.swing.JPanel();
        textArea03ScrollPane = new javax.swing.JScrollPane();
        panel03TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackGroundPanel.setBackground(new java.awt.Color(0, 51, 51));

        TittleLabe.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TittleLabe.setForeground(new java.awt.Color(204, 255, 255));
        TittleLabe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TittleLabe.setText("Xableiros Assistente");

        FooterLabel.setForeground(new java.awt.Color(153, 255, 153));
        FooterLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        FooterLabel.setText("Iel Rebeque @fullmigasamurai  ");

        tellYouLabel.setForeground(new java.awt.Color(255, 255, 255));
        tellYouLabel.setText("Te Falar:");

        messageLabel.setBackground(new java.awt.Color(255, 255, 255));
        messageLabel.setForeground(new java.awt.Color(153, 255, 255));
        messageLabel.setText("Nada;");

        dsTabPanel.setBackground(new java.awt.Color(51, 51, 51));
        dsTabPanel.setMaximumSize(new java.awt.Dimension(180, 178));
        dsTabPanel.setMinimumSize(new java.awt.Dimension(100, 100));

        readDsButton.setText("CarregaArquivos");
        readDsButton.setToolTipText("Reads a aconfig file. gets the name from conf");
        readDsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readDsButtonActionPerformed(evt);
            }
        });

        replaceDsButton.setText("Substitui");
        replaceDsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceDsButtonActionPerformed(evt);
            }
        });

        dsPathList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dsPathListMouseClicked(evt);
            }
        });
        dsPathList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dsPathListKeyPressed(evt);
            }
        });
        dsPathScrollPanel.setViewportView(dsPathList);

        viewButton.setText(" Visualiza");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Salva");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        saveAsButton.setText("Salva...");
        saveAsButton.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(42, 42, 42));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 153, 51), null, null)));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 134));

        comumCheckBox.setBackground(new java.awt.Color(51, 51, 51));
        comumCheckBox.setForeground(new java.awt.Color(0, 153, 102));
        comumCheckBox.setText("Comum");

        contratoCheckBox.setBackground(new java.awt.Color(51, 51, 51));
        contratoCheckBox.setForeground(new java.awt.Color(0, 153, 102));
        contratoCheckBox.setText("Contrato");

        patrimonioCheckBox.setBackground(new java.awt.Color(51, 51, 51));
        patrimonioCheckBox.setForeground(new java.awt.Color(0, 153, 102));
        patrimonioCheckBox.setText("Patrimonio");

        copyDsLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        copyDsLabel.setForeground(new java.awt.Color(153, 255, 153));
        copyDsLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        copyDsLabel.setText("Copia DS:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comumCheckBox)
                    .addComponent(contratoCheckBox)
                    .addComponent(patrimonioCheckBox)
                    .addComponent(copyDsLabel))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(copyDsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(comumCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contratoCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(patrimonioCheckBox)
                .addContainerGap())
        );

        javax.swing.GroupLayout dsTabPanelLayout = new javax.swing.GroupLayout(dsTabPanel);
        dsTabPanel.setLayout(dsTabPanelLayout);
        dsTabPanelLayout.setHorizontalGroup(
            dsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(readDsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(replaceDsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dsPathScrollPanel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dsTabPanelLayout.createSequentialGroup()
                        .addComponent(viewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveAsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dsTabPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dsTabPanelLayout.setVerticalGroup(
            dsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dsTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(readDsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dsPathScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewButton)
                    .addComponent(saveButton)
                    .addComponent(saveAsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(replaceDsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        rightTabbedPane.addTab("DS", dsTabPanel);

        scriptsTabPanel.setBackground(new java.awt.Color(51, 51, 51));

        idDoContratoText.setToolTipText("PODE SER INFORMADO MAIS DE 1 ID SEPARADO POR VIRGULA EX:[42,64,72]");

        idDoContratoLabel.setForeground(new java.awt.Color(102, 255, 153));
        idDoContratoLabel.setText("Id Do Contrato:");

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Gerar Exclusão");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(51, 51, 51));
        dataBaseTypeButtonGroup.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(102, 255, 153));
        jRadioButton1.setText("Mssql");

        jRadioButton2.setBackground(new java.awt.Color(51, 51, 51));
        dataBaseTypeButtonGroup.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(102, 255, 153));
        jRadioButton2.setText("Oracle");

        jRadioButton3.setBackground(new java.awt.Color(51, 51, 51));
        dataBaseTypeButtonGroup.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(102, 255, 153));
        jRadioButton3.setText("Postgres");
        jRadioButton3.setEnabled(false);

        javax.swing.GroupLayout scriptsTabPanelLayout = new javax.swing.GroupLayout(scriptsTabPanel);
        scriptsTabPanel.setLayout(scriptsTabPanelLayout);
        scriptsTabPanelLayout.setHorizontalGroup(
            scriptsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptsTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scriptsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(scriptsTabPanelLayout.createSequentialGroup()
                        .addComponent(idDoContratoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(idDoContratoText, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(scriptsTabPanelLayout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        scriptsTabPanelLayout.setVerticalGroup(
            scriptsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(scriptsTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(scriptsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idDoContratoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDoContratoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(scriptsTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        rightTabbedPane.addTab("Scripts", scriptsTabPanel);

        repoTabPanel.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout repoTabPanelLayout = new javax.swing.GroupLayout(repoTabPanel);
        repoTabPanel.setLayout(repoTabPanelLayout);
        repoTabPanelLayout.setHorizontalGroup(
            repoTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        repoTabPanelLayout.setVerticalGroup(
            repoTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );

        rightTabbedPane.addTab("Repo", repoTabPanel);

        configTabPanel.setBackground(new java.awt.Color(51, 51, 51));

        pathDsLabel.setForeground(new java.awt.Color(102, 255, 153));
        pathDsLabel.setText("Caminho DS:");

        pathDsText.setToolTipText("Select a confgiguration file. csv type, two columns");
        pathDsText.setMaximumSize(new java.awt.Dimension(180, 25));
        pathDsText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathDsTextMouseClicked(evt);
            }
        });
        pathDsText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pathDsTextKeyPressed(evt);
            }
        });

        pathDeployText.setToolTipText("Select a confgiguration file. csv type, two columns");
        pathDeployText.setMaximumSize(new java.awt.Dimension(180, 25));
        pathDeployText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pathDeployTextMouseClicked(evt);
            }
        });
        pathDeployText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pathDeployTextKeyPressed(evt);
            }
        });

        pathDeployLabel.setForeground(new java.awt.Color(102, 255, 153));
        pathDeployLabel.setText("Caminho Deploy:");

        saveConfigFile.setText("Salvar Alterações");
        saveConfigFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveConfigFileActionPerformed(evt);
            }
        });

        backGroundColorLabel.setForeground(new java.awt.Color(102, 255, 153));
        backGroundColorLabel.setText("Cor De Fundo:");

        backGroundColorText.setToolTipText("Select a confgiguration file. csv type, two columns");
        backGroundColorText.setMaximumSize(new java.awt.Dimension(180, 25));
        backGroundColorText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backGroundColorTextMouseClicked(evt);
            }
        });
        backGroundColorText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                backGroundColorTextKeyPressed(evt);
            }
        });

        foreGroundColorLabel.setForeground(new java.awt.Color(102, 255, 153));
        foreGroundColorLabel.setText("Cor Do Texto:");

        foreGroundColorText.setToolTipText("Select a confgiguration file. csv type, two columns");
        foreGroundColorText.setMaximumSize(new java.awt.Dimension(180, 25));
        foreGroundColorText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                foreGroundColorTextMouseClicked(evt);
            }
        });
        foreGroundColorText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                foreGroundColorTextKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout configTabPanelLayout = new javax.swing.GroupLayout(configTabPanel);
        configTabPanel.setLayout(configTabPanelLayout);
        configTabPanelLayout.setHorizontalGroup(
            configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configTabPanelLayout.createSequentialGroup()
                        .addGroup(configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pathDeployLabel)
                            .addComponent(pathDsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pathDeployText, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(pathDsText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configTabPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveConfigFile))
                    .addGroup(configTabPanelLayout.createSequentialGroup()
                        .addComponent(backGroundColorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backGroundColorText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(foreGroundColorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foreGroundColorText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        configTabPanelLayout.setVerticalGroup(
            configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configTabPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pathDsText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pathDsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pathDeployText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pathDeployLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(foreGroundColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(foreGroundColorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(configTabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backGroundColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backGroundColorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(saveConfigFile)
                .addContainerGap())
        );

        rightTabbedPane.addTab("Configuracoes", configTabPanel);

        FooterLabel1.setForeground(new java.awt.Color(153, 255, 153));
        FooterLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        FooterLabel1.setText("Até Mais E Obrigada Pelos Peixes!");

        leftTabbedPanel.setToolTipText("");

        firstTabTablePanel.setBackground(new java.awt.Color(51, 0, 51));

        panel01TextArea.setBackground(new java.awt.Color(49, 0, 73));
        panel01TextArea.setColumns(20);
        panel01TextArea.setForeground(new java.awt.Color(51, 255, 51));
        panel01TextArea.setRows(5);
        textArea01ScrollPane2.setViewportView(panel01TextArea);

        javax.swing.GroupLayout firstTabTablePanelLayout = new javax.swing.GroupLayout(firstTabTablePanel);
        firstTabTablePanel.setLayout(firstTabTablePanelLayout);
        firstTabTablePanelLayout.setHorizontalGroup(
            firstTabTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstTabTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArea01ScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
        );
        firstTabTablePanelLayout.setVerticalGroup(
            firstTabTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstTabTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArea01ScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        leftTabbedPanel.addTab("sigacomum-ds", firstTabTablePanel);

        secondTabTablePanel.setBackground(new java.awt.Color(51, 0, 51));

        panel02TextArea.setBackground(new java.awt.Color(49, 0, 73));
        panel02TextArea.setColumns(20);
        panel02TextArea.setForeground(new java.awt.Color(51, 255, 51));
        panel02TextArea.setRows(5);
        textArea02ScrollPane.setViewportView(panel02TextArea);

        javax.swing.GroupLayout secondTabTablePanelLayout = new javax.swing.GroupLayout(secondTabTablePanel);
        secondTabTablePanel.setLayout(secondTabTablePanelLayout);
        secondTabTablePanelLayout.setHorizontalGroup(
            secondTabTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondTabTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArea02ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
        );
        secondTabTablePanelLayout.setVerticalGroup(
            secondTabTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondTabTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArea02ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        leftTabbedPanel.addTab("sigacontrato-ds", secondTabTablePanel);

        thirdTabTablePanel.setBackground(new java.awt.Color(51, 0, 51));

        panel03TextArea.setBackground(new java.awt.Color(49, 0, 73));
        panel03TextArea.setColumns(20);
        panel03TextArea.setForeground(new java.awt.Color(51, 255, 51));
        panel03TextArea.setRows(5);
        textArea03ScrollPane.setViewportView(panel03TextArea);

        javax.swing.GroupLayout thirdTabTablePanelLayout = new javax.swing.GroupLayout(thirdTabTablePanel);
        thirdTabTablePanel.setLayout(thirdTabTablePanelLayout);
        thirdTabTablePanelLayout.setHorizontalGroup(
            thirdTabTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdTabTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArea03ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
        );
        thirdTabTablePanelLayout.setVerticalGroup(
            thirdTabTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdTabTablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textArea03ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        leftTabbedPanel.addTab("sigapatrimonio-ds", thirdTabTablePanel);

        javax.swing.GroupLayout BackGroundPanelLayout = new javax.swing.GroupLayout(BackGroundPanel);
        BackGroundPanel.setLayout(BackGroundPanelLayout);
        BackGroundPanelLayout.setHorizontalGroup(
            BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPanelLayout.createSequentialGroup()
                .addGroup(BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackGroundPanelLayout.createSequentialGroup()
                        .addComponent(TittleLabe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FooterLabel1))
                    .addGroup(BackGroundPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackGroundPanelLayout.createSequentialGroup()
                                .addComponent(leftTabbedPanel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rightTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BackGroundPanelLayout.createSequentialGroup()
                                .addComponent(tellYouLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(messageLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FooterLabel)))))
                .addContainerGap())
        );
        BackGroundPanelLayout.setVerticalGroup(
            BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundPanelLayout.createSequentialGroup()
                .addGroup(BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TittleLabe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FooterLabel1))
                .addGap(18, 18, 18)
                .addGroup(BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(rightTabbedPane))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FooterLabel)
                    .addComponent(tellYouLabel)
                    .addComponent(messageLabel))
                .addContainerGap())
        );

        rightTabbedPane.getAccessibleContext().setAccessibleName("TabManager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackGroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readDsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readDsButtonActionPerformed
        assistenteJanela.loadDsDirectories();
    }//GEN-LAST:event_readDsButtonActionPerformed

    private void replaceDsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceDsButtonActionPerformed
        String dsDir = dsPathList.getSelectedValue();
        assistenteJanela.copyDsFiles(dsDir);
    }//GEN-LAST:event_replaceDsButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        String dsDir = dsPathList.getSelectedValue();
        assistenteJanela.getDsFiles(dsDir);
    }//GEN-LAST:event_viewButtonActionPerformed

    private void pathDsTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathDsTextMouseClicked
        if (evt.getClickCount() == 2) {
            String newPath = assistenteJanela.getFolderPath("DS");
            if (newPath != null && !newPath.equals("")) {
                pathDsText.setText(newPath);
                assistenteJanela.loadDsDirectories();
            }
        }
    }//GEN-LAST:event_pathDsTextMouseClicked

    private void pathDsTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathDsTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (pathDsText.getText().isEmpty()) {
                pathDsText.setText(assistenteJanela.getFolderPath("DS"));
            }
            assistenteJanela.loadDsDirectories();
        }
    }//GEN-LAST:event_pathDsTextKeyPressed

    private void pathDeployTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pathDeployTextMouseClicked
        if (evt.getClickCount() == 2) {
            pathDeployText.setText(assistenteJanela.getFolderPath("Deploy"));
        }
    }//GEN-LAST:event_pathDeployTextMouseClicked

    private void pathDeployTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathDeployTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (pathDeployText.getText().isEmpty()) {
                pathDeployText.setText(assistenteJanela.getFolderPath("DS"));
            }
            
        }
    }//GEN-LAST:event_pathDeployTextKeyPressed

    private void saveConfigFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveConfigFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveConfigFileActionPerformed

    private void dsPathListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dsPathListMouseClicked
        // int index = dsPathList.getSelectedIndex();
        String dsDir = dsPathList.getSelectedValue();
        assistenteJanela.getDsFiles(dsDir);
    }//GEN-LAST:event_dsPathListMouseClicked

    private void dsPathListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dsPathListKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER && evt.getModifiersEx() == java.awt.event.InputEvent.CTRL_DOWN_MASK) {        
            String dsDir = dsPathList.getSelectedValue();
            assistenteJanela.copyDsFiles(dsDir);
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String dsDir = dsPathList.getSelectedValue();
            assistenteJanela.getDsFiles(dsDir);
        }
    }//GEN-LAST:event_dsPathListKeyPressed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int index = leftTabbedPanel.getSelectedIndex();        
        assistenteJanela.saveDs(leftTabbedPanel.getTitleAt(index));
    }//GEN-LAST:event_saveButtonActionPerformed

    private void backGroundColorTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backGroundColorTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backGroundColorTextMouseClicked

    private void backGroundColorTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_backGroundColorTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_backGroundColorTextKeyPressed

    private void foreGroundColorTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_foreGroundColorTextMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_foreGroundColorTextMouseClicked

    private void foreGroundColorTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_foreGroundColorTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_foreGroundColorTextKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        assistenteJanela.generateDeleteScriptContrato(this.idDoContratoText.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private AssistenteJanela assistenteJanela;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JLabel FooterLabel;
    private javax.swing.JLabel FooterLabel1;
    private javax.swing.JLabel TittleLabe;
    private javax.swing.JLabel backGroundColorLabel;
    public javax.swing.JTextField backGroundColorText;
    public javax.swing.JCheckBox comumCheckBox;
    private javax.swing.JPanel configTabPanel;
    public javax.swing.JCheckBox contratoCheckBox;
    private javax.swing.JLabel copyDsLabel;
    private javax.swing.ButtonGroup dataBaseTypeButtonGroup;
    public javax.swing.JList<String> dsPathList;
    private javax.swing.JScrollPane dsPathScrollPanel;
    private javax.swing.JPanel dsTabPanel;
    private javax.swing.JPanel firstTabTablePanel;
    private javax.swing.JLabel foreGroundColorLabel;
    public javax.swing.JTextField foreGroundColorText;
    private javax.swing.JLabel idDoContratoLabel;
    public javax.swing.JTextField idDoContratoText;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTabbedPane leftTabbedPanel;
    public javax.swing.JLabel messageLabel;
    public javax.swing.JTextArea panel01TextArea;
    public javax.swing.JTextArea panel02TextArea;
    public javax.swing.JTextArea panel03TextArea;
    private javax.swing.JLabel pathDeployLabel;
    public javax.swing.JTextField pathDeployText;
    private javax.swing.JLabel pathDsLabel;
    public javax.swing.JTextField pathDsText;
    public javax.swing.JCheckBox patrimonioCheckBox;
    private javax.swing.JButton readDsButton;
    private javax.swing.JButton replaceDsButton;
    private javax.swing.JPanel repoTabPanel;
    private javax.swing.JTabbedPane rightTabbedPane;
    private javax.swing.JButton saveAsButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveConfigFile;
    private javax.swing.JPanel scriptsTabPanel;
    private javax.swing.JPanel secondTabTablePanel;
    private javax.swing.JLabel tellYouLabel;
    private javax.swing.JScrollPane textArea01ScrollPane2;
    private javax.swing.JScrollPane textArea02ScrollPane;
    private javax.swing.JScrollPane textArea03ScrollPane;
    private javax.swing.JPanel thirdTabTablePanel;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
