INSERT INTO DB_CONTRATOS.dbo.TB_ITEM_CONTRATO (IC_ID_ORIGINAL, AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, IC_QUANTIDADE,
                                               IC_QUANTIDADE_ATUAL, IC_QUANTIDADE_EXECUTADA, IC_VALOR, IC_VALOR_ANTERIOR, IC_VALOR_TOTAL, IC_VALOR_TOTAL_ATUAL,
                                               IC_VALOR_TOTAL_ATUAL_ANTERIOR, IC_VALOR_TOTAL_EXECUTADO, IC_NUM_SEQUENCIA, IC_STR_SEQUENCIA, IC_DESCRICAO, IC_CODIGO, IC_UNIDADE,
                                               IC_ID_PAI, IC_GRUPO, IC_EXPANDIDO, IC_RETROATIVO, FK_IC_CONT, IC_VERSION, IC_ORIGEM_COMPRA, IC_NATUREZA_DESPESA, IC_TIPO_ITEM, item_cont_id_216,
                                               IC_ORIGEM_IMPORTADO_PROCESSO, IC_AC_QUANTIDADE_ALTERACAO, IC_AC_VALOR_UN_ALTERACAO, IC_AC_VALOR_TOTAL_ALTERACAO)
VALUES (NULL, N'2022-12-05 08:30:23.740', null, N'gcont.admin', N'gcont.admin', 1.00000000, 1.00000000, 0.00000000,
        2.56000000, 0.00000000, 2.56000000, 2.56000000, null, 0.00000000, 1000000, N'1',
        N'Caneta esferográfica personalizável com impressão monocromática, corpo em plástico na cor branca, gripe emborrachado na mesma cor do clipe, medindo aproximadamente 13 cm, escrita azul.',
        N'81911', N'Unidade', null, N'N', N'N', N'ITEM_NAO_REAJUSTADO', idContratoSubstituir, 0, N'S', N'33903299', N'FIXO', null,
        N'N', null, null, null);


update TB_CONT
    set CONT_VAL_ATUAL_CONTRATO=(SELECT SUM (IC_VALOR_TOTAL_ATUAL) FROM TB_ITEM_CONTRATO WHERE FK_IC_CONT = idContratoSubstituir),
    CONT_VAL_INICIAL_CONTRATO=(SELECT SUM (IC_VALOR_TOTAL_ATUAL) FROM TB_ITEM_CONTRATO WHERE FK_IC_CONT = 48364)
where CONT_ID=idContratoSubstituir;



INSERT INTO DB_CONTRATOS.dbo.TB_CONTRATO_DOTACAO (CONT_ID, DOT_ID, CD_ID_ORIGEM, CD_PRE_EMPENHO, CD_SITUACAO_PRE_EMPENHO)
VALUES (idContratoSubstituir, (SELECT TOP 1 DOT_ID FROM TB_DOTACAO_ORCAMENTARIA ORDER BY DOT_ID DESC), null, null, null);


INSERT INTO DB_CONTRATOS.dbo.TB_EMPENHO (EM_ID_ORIGEM, EM_TIPO, EM_NUMERO, EM_VALOR_GLOBAL, EM_DATA_EMISSAO, EM_SITUACAO, EM_ANULADO, FK_EM_DOT, FK_EM_CONT, AUD_DATA_CRIACAO,
                                         AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, EM_TIPO_FORN, EM_FORN_TIPO_PESSOA, EM_FORN_CNPJ_CPF, EM_FORN_RAZAO_SOCIAL,
                                         EM_FORN_NOME_FANTASIA, EM_FORN_LOGRA, EM_FORN_LOGRA_NUM, EM_FORN_BAIRRO, EM_FORN_ESTADO, EM_FORN_ID_MUNICIPIO, EM_FORN_CEP, EM_FORN_TELEFONE,
                                         EM_FORN_EMAIL, EM_ID_216, EM_ID_ORGAO, EM_REFORCO_INVIDUAL, EM_INTEGRACAO, EM_VALOR_ORIGINAL, EM_FRACIONADO)
VALUES (NULL, N'ORDINARIO', N'42424242', 42.00000000, N'2023-01-27 00:00:00.000', N'ATIVO', null, (SELECT TOP 1 DOT_ID FROM TB_DOTACAO_ORCAMENTARIA ORDER BY DOT_ID DESC), idContratoSubstituir,
        GETDATE(), null, N'gcont.admin', N'gcont.admin', N'Fornecedor Contrato', N'J',
        N'01632236000103', N'DOIS IRMÃOS AUTO', N'FORNECEDOR TESTE 3', N'RUA 1', N'22', N'CENTRO', N'ES', 3165,
        N'11111-111', N'(11) 11111-1111', N'hkanno@azi.srv.br', null, 1, N'N', N'N', 42.00, null);


INSERT INTO DB_CONTRATOS.dbo.TB_EVENTO (EV_DESCRICAO, EV_USUARIO_CADASTRO, EV_USUARIO_EXECUCAO, EV_DATA_CADASTRO,
                                        EV_DATA_INICIAL, EV_DATA_FINAL, EV_TIPO, EV_TIPO_EXECUCAO, EV_SITUACAO, CONT_ID)
VALUES (N'Novo empenho com identificador 42424242 adicionado ao contrato null', N'gcont.admin', null,
        N'2022-12-05 08:48:30.333', null, null, N'EMPENHO_ADICIONADO', N'LANCAMENTO', N'ATIVO', idContratoSubstituir);


INSERT INTO DB_CONTRATOS.dbo.TB_ASSINATURA (AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, ASS_NOME, ASS_CARGO, ASS_CPF,
                                            ASS_TIPO_ASSINATURA, ASS_ORGAO_EXPEDIDOR, ASS_RG, ASS_ENDERECO, ASS_NUMERO, ASS_ESTADO, ASS_ID_MUNICIPIO, ASS_IMPRESSO_PREAMBULO, FK_ASS_EX,
                                            FK_ASS_CONT, ASS_FORN_TIPO_PESSOA, ASS_FORN_CNPJ_CPF, ASS_FORN_RAZAO_SOCIAL, ASS_FORN_NOME_FANTASIA, ASS_FORN_LOGRA, ASS_FORN_LOGRA_NUM, ASS_FORN_BAIRRO,
                                            ASS_FORN_ESTADO, ASS_FORN_ID_MUNICIPIO, ASS_FORN_CEP, ASS_FORN_TELEFONE, ASS_FORN_EMAIL, ASS_ID_ORIGEM, FK_ASS_CONT_ES)
VALUES (GETDATE(), null, N'gcont.admin', N'gcont.admin', N'Administrador do contratos', N'CHEFE',
        N'51056138050', N'ORGAO', N'SSPMS', N'18865560', N'RUA DOS BOBOS', N'0', N'MS', 5076, N'S', null, idContratoSubstituir, null,
        null, null, null, null, null, null, null, null, null, null, null, null, null);


INSERT INTO DB_CONTRATOS.dbo.TB_ASSINATURA (AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, ASS_NOME, ASS_CARGO, ASS_CPF,
                                            ASS_TIPO_ASSINATURA, ASS_ORGAO_EXPEDIDOR, ASS_RG, ASS_ENDERECO, ASS_NUMERO, ASS_ESTADO, ASS_ID_MUNICIPIO, ASS_IMPRESSO_PREAMBULO, FK_ASS_EX,
                                            FK_ASS_CONT, ASS_FORN_TIPO_PESSOA, ASS_FORN_CNPJ_CPF, ASS_FORN_RAZAO_SOCIAL, ASS_FORN_NOME_FANTASIA, ASS_FORN_LOGRA, ASS_FORN_LOGRA_NUM, ASS_FORN_BAIRRO,
                                            ASS_FORN_ESTADO, ASS_FORN_ID_MUNICIPIO, ASS_FORN_CEP, ASS_FORN_TELEFONE, ASS_FORN_EMAIL, ASS_ID_ORIGEM, FK_ASS_CONT_ES)
VALUES (GETDATE(), null, N'gcont.admin', N'gcont.admin', N'MARIO & LUIGI', N'CHEFE', N'12245578860',
        N'CONTRATADO', N'SSPMS', N'46687765', N'REINO DOS COGUMELOS', N'333', N'AC', 53, N'S', null, idContratoSubstituir, N'J', N'01632236000103', N'DOIS IRMÃOS AUTO',
        N'FORNECEDOR TESTE 3', N'RUA 1', N'22', N'CENTRO', N'ES', 3165, N'11111-111', N'(11) 11111-1111', N'hkanno@azi.srv.br', null, null);


--FAZER A CONDIÇÃO PARA VERIFICAR SE JÁ EXISTE UMA MINUTA PARA O CONTRATO
INSERT INTO DB_CONTRATOS.dbo.TB_MINUTA_CONTRATO (MC_DATA_CRIACAO, MC_ORGAO_ID, MC_SITUACAO, MC_TITULO, MC_EMENTA, MC_PREAMBULO, MC_EDITADO_EMENTA,
                                                 MC_EDITADO_PREAMBULO, CONT_ID, MC_ID_216, MC_TIPO, CONTE_ID, MC_EDITADO_RODAPE, MC_RODAPE)
VALUES (GETDATE(), 1, N'ATIVO', N'Minuta',
        N'Contratos que entre si celebram Leitor e a empresa D D LIMPE DEDETIZADORA LTDA ME, DOIS IRMÃOS AUTO, tendo por objeto, OBJETO, conforme edital e seus anexos.',
        N'O ESTADO DE   Mato Grosso do Sul por meio da(o) Leitor, doravante denominada Contratante, com sede no(a) 01, 0, Centro, Cuiabá - MT, inscrita no CNPJ sob nº 85.772.112/0001-13, neste ato representado por Administrador do contratos, residente na RUA DOS BOBOS, nº 0 no município de Bonito – MS, portador do RG nº 18865560 e do CPF nº 510.561.380-50, e de outro lado ${fornecedorCompleto}, considerando a autorização para aquisição do objeto de que trata o processo nº 07090895000141, resolvem celebrar o presente Contrato, que será regido pela Lei nº 8.666, de 21/06/1993 e suas alterações posteriores e, no que couber, a lei nº 10.520, de 17/07/2002, assim como, supletivamente, pelos princípios da teoria geral dos contratos, pelas disposições de direito privado e pelas cláusulas e condições a seguir delineadas:',
        N'N', N'N', idContratoSubstituir, null, N'CONTRATO', null, N'N',
        N'E, por se acharem justas e contratadas, as partes assinam o presente instrumento na presença das testemunhas abaixo, em 2 (duas) vias de igual teor e forma, para que produza todos os efeitos legais.');


INSERT INTO DB_CONTRATOS.dbo.TB_ASSINATURA (AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, ASS_NOME, ASS_CARGO, ASS_CPF,
                                            ASS_TIPO_ASSINATURA, ASS_ORGAO_EXPEDIDOR, ASS_RG, ASS_ENDERECO, ASS_NUMERO, ASS_ESTADO, ASS_ID_MUNICIPIO, ASS_IMPRESSO_PREAMBULO, FK_ASS_EX,
                                            FK_ASS_CONT, ASS_FORN_TIPO_PESSOA, ASS_FORN_CNPJ_CPF, ASS_FORN_RAZAO_SOCIAL, ASS_FORN_NOME_FANTASIA, ASS_FORN_LOGRA, ASS_FORN_LOGRA_NUM, ASS_FORN_BAIRRO,
                                            ASS_FORN_ESTADO, ASS_FORN_ID_MUNICIPIO, ASS_FORN_CEP, ASS_FORN_TELEFONE, ASS_FORN_EMAIL, ASS_ID_ORIGEM, FK_ASS_CONT_ES)
VALUES (GETDATE(), null, N'gcont.admin', N'gcont.admin', N'MARIO & LUIGI', N'CHEFE',
        N'12245578860', N'CONTRATADO', N'SSPMS', N'46687765', N'REINO DOS COGUMELOS', N'333', N'AC', 53, N'S', null,
        idContratoSubstituir, N'J', N'01632236000103', N'DOIS IRMÃOS AUTO', N'FORNECEDOR TESTE 3', N'RUA 1', N'22', N'CENTRO', N'ES',
        3165, N'11111-111', N'(11) 11111-1111', N'hkanno@azi.srv.br', null, null);


INSERT INTO DB_CONTRATOS.dbo.TB_CLAUSULA_CONTRATO (CC_TITULO, MC_ID, CC_DESCRICAO, CC_SEQUENCIA, CC_ID_PAI, CC_EDITADO, CC_TABELA, CC_TIPO, CC_FLY_ID)
VALUES (null, (SELECT TOP 1 MC_ID FROM TB_MINUTA_CONTRATO WHERE CONT_ID = idContratoSubstituir ORDER BY MC_ID DESC), null, N'01000000', null, N'N', null, null, null);


INSERT INTO DB_CONTRATOS.dbo.TB_MEDICAO (MD_ID_ORIGEM, AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, MD_NUMERO_BOLETIM, MD_SEQUENCIA, MD_DURACAO, MD_SITUACAO_MEDICAO,
                                         MD_PERIODO_INICIAL, MD_PERIODO_FINAL,
                                         MD_DATA_MEDICAO, CONT_ID, MD_PERIODICIDADE, parc_cont_id_216)
VALUES (null, GETDATE(), null, N'gcont.admin', N'gcont.admin', null, 1, 728, N'ABERTA',
        (SELECT TOP 1 CONT_DATA_INI_VIGENCIA FROM TB_CONT WHERE CONT_ID = idContratoSubstituir), (SELECT TOP 1 CONT_DATA_FIM_VIGENCIA FROM TB_CONT WHERE CONT_ID = idContratoSubstituir),
        null, idContratoSubstituir, N'INTEGRAL', null);



INSERT INTO DB_CONTRATOS.dbo.TB_PARCELA_CONTRATO (PC_ID_ORIGEM, AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, PC_TIPO,
                                                  PC_NUM_PARCELA, PC_QTD_DIAS_APOS_MED, PC_VALOR, PC_DT_VENC, CONT_ID, MD_ID, parc_cont_id_216, PC_VALOR_ANTERIOR_ALTERACAO,
                                                  PC_VALOR_ALTERACAO, PC_MOTIVO_NAO_SOLICITACAO, PC_USUARIO_NAO_SOLICITACAO, PC_DATA_NAO_SOLICITACAO)
VALUES (null, GETDATE(), null, N'gcont.admin', N'gcont.admin', N'ITEM', 1, 0, 2.56000000,
        (SELECT TOP 1 CONT_DATA_FIM_VIGENCIA FROM TB_CONT WHERE CONT_ID = idContratoSubstituir), idContratoSubstituir,
        (SELECT TOP 1 MD_ID FROM TB_MEDICAO WHERE CONT_ID = idContratoSubstituir), null, null, null, null, null, null);


INSERT INTO DB_CONTRATOS.dbo.TB_PARC_CONT_DOT_ORC (VALOR_UTILIZADO, PC_ID, DOT_ID, PARC_CONT_DOT_ORC_ID_ORIGEM, VALOR_ANTERIOR_ALTERACAO)
VALUES (0.00000000, (SELECT TOP 1 PC_ID FROM TB_PARCELA_CONTRATO WHERE CONT_ID = idContratoSubstituir ORDER BY PC_ID DESC),
        (SELECT TOP 1 DOT_ID FROM TB_CONTRATO_DOTACAO WHERE CONT_ID = idContratoSubstituir ORDER BY DOT_ID DESC), null, null);


INSERT INTO DB_CONTRATOS.dbo.TB_PARC_CONT_EMP (VALOR_UTILIZADO, PC_ID, EM_ID, PARC_CONT_EMP_ID_ORIGEM, VALOR_ANTERIOR_ALT)
VALUES (2.56000000, (SELECT TOP 1 PC_ID FROM TB_PARCELA_CONTRATO WHERE CONT_ID = idContratoSubstituir ORDER BY PC_ID DESC),
        (SELECT TOP 1 EM_ID FROM TB_EMPENHO WHERE FK_EM_CONT = idContratoSubstituir ORDER BY EM_ID DESC),
        null, null);


--INSERE DATA DE ASSINATURA
update
    TB_CONT
set
    CONT_DATA_ASSINATURA=GETDATE()
where
        CONT_ID=idContratoSubstituir

--ENVIAR PARA CELEBRACAO
update
    TB_CONT
set
    WFK_CONT_AI='A2'
where
        CONT_ID=idContratoSubstituir


INSERT INTO DB_CONTRATOS.dbo.TB_ORDEM_SERVICO (OS_TIPO, OS_SEQUENCIAL, OS_ANO, OS_DATA_EMISSAO, OS_JUSTIFICATIVA_PARALISACAO, FK_OS_CONT,
                                               OS_JUSTIFICATIVA_CANCELAMENTO, OS_SITUACAO, OS_QTDE_DIAS, OS_DATA_TERMINO)
VALUES (N'INICIO', 1, 2022, N'2022-11-30 00:00:00.000', null, idContratoSubstituir, null, N'ATIVO', null, null);


INSERT INTO DB_CONTRATOS.dbo.TB_CELEBRACAO (AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, CLB_OBSERVACAO, CLB_DATA_CELEBRACAO,
                                            CLB_ORDEM_INICIO, CLB_CANCELADO, CLB_MOTIVO_CANCEL, CLB_RESPONSAVEL_CANCEL, CLB_DATA_CANCEL, FK_CLB_CONT)
VALUES (GETDATE(), null, N'gcont.admin', N'gcont.admin', N'ORGANIZAÇÃO MERIONAL PARALELA QUANTICA OLISTICA',
        GETDATE(), N'S', N'N', null, null, null, idContratoSubstituir);


INSERT INTO DB_CONTRATOS.dbo.TB_REVISAO (DATA_ALTERACAO, USUARIO_ALTERACAO, MOTIVO_ALTERACAO, CONT_ID)
VALUES (GETDATE(), N'gcont.admin', N'Celebração do Contrato.', idContratoSubstituir);


--ALTERAR STATUS CELEBRADO
update
    TB_CONT
set
    CONT_SITUACAO_CONTRATO='CELEBRADO',
    AUD_DATA_ULT_ALTERACAO=GETDATE()

where
    CONT_ID=idContratoSubstituir


INSERT INTO DB_CONTRATOS.dbo.TB_EVENTO (EV_DESCRICAO, EV_USUARIO_CADASTRO, EV_USUARIO_EXECUCAO, EV_DATA_CADASTRO,
                                        EV_DATA_INICIAL, EV_DATA_FINAL, EV_TIPO, EV_TIPO_EXECUCAO, EV_SITUACAO, CONT_ID)
VALUES (N'Celebração do contrato NUMER-DO-CONTRATO', N'gcont.admin', null, GETDATE(), null, null,
        N'CONTRATO_CELEBRAR', N'LANCAMENTO', N'ATIVO', idContratoSubstituir);


INSERT INTO DB_CONTRATOS.dbo.AUD_TB_MEDICAO (MD_ID, REV_ID, TIPO_REVISAO, AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO,
                                             AUD_USUARIO_ULT_ALTERACAO, MD_ID_ORIGEM, MD_NUMERO_BOLETIM, MD_SEQUENCIA, MD_DURACAO,
                                             MD_SITUACAO_MEDICAO, MD_PERIODO_INICIAL, MD_PERIODO_FINAL, MD_DATA_MEDICAO, CONT_ID, MD_PERIODICIDADE)
VALUES ((SELECT TOP 1 MD_ID FROM TB_MEDICAO WHERE CONT_ID = idContratoSubstituir ORDER BY MD_ID DESC), (SELECT TOP 1 REV_ID FROM TB_REVISAO WHERE CONT_ID = idContratoSubstituir ORDER BY REV_ID DESC),
        1, GETDATE(), GETDATE(), N'gcont.admin', N'gcont.admin', null, null,
        (SELECT TOP 1 MD_SEQUENCIA FROM TB_MEDICAO WHERE CONT_ID = idContratoSubstituir ORDER BY MD_ID DESC),
        (SELECT TOP 1 MD_DURACAO FROM TB_MEDICAO WHERE CONT_ID = idContratoSubstituir ORDER BY MD_ID ASC),
        (SELECT TOP 1 MD_SITUACAO_MEDICAO FROM TB_MEDICAO WHERE CONT_ID = idContratoSubstituir ORDER BY MD_ID ASC),
        (SELECT TOP 1 MD_PERIODO_INICIAL FROM TB_MEDICAO WHERE CONT_ID = idContratoSubstituir ORDER BY MD_ID ASC),
        (SELECT TOP 1 MD_PERIODO_INICIAL FROM TB_MEDICAO WHERE CONT_ID = idContratoSubstituir ORDER BY MD_ID ASC),
        null, idContratoSubstituir,
        (SELECT TOP 1 MD_PERIODO_INICIAL FROM TB_MEDICAO WHERE CONT_ID = idContratoSubstituir ORDER BY MD_ID ASC));


INSERT INTO DB_CONTRATOS.dbo.AUD_TB_ITEM_CONTRATO (IC_ID, REV_ID, TIPO_REVISAO, AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO,
                                                   IC_QUANTIDADE, IC_QUANTIDADE_ATUAL, IC_QUANTIDADE_EXECUTADA, IC_VALOR, IC_VALOR_ANTERIOR, IC_VALOR_TOTAL,
                                                   IC_VALOR_TOTAL_ATUAL, IC_VALOR_EXECUTADO, IC_NUM_SEQUENCIA, IC_STR_SEQUENCIA, IC_DESCRICAO, IC_CODIGO, IC_UNIDADE, IC_ID_PAI,
                                                   IC_GRUPO, IC_EXPANDIDO, IC_RETROATIVO, FK_IC_CONT, IC_VERSION, IC_ID_ORIGINAL, IC_VALOR_TOTAL_ATUAL_ANTERIOR,
                                                   IC_VALOR_TOTAL_EXECUTADO, IC_ORIGEM_COMPRA, IC_NATUREZA_DESPESA, IC_TIPO_ITEM, IC_ORIGEM_IMPORTADO_PROCESSO,
                                                   IC_AC_QUANTIDADE_ALTERACAO, IC_AC_VALOR_UN_ALTERACAO, IC_AC_VALOR_TOTAL_ALTERACAO)
VALUES ((SELECT TOP 1 IC_ID FROM TB_ITEM_CONTRATO WHERE FK_IC_CONT = idContratoSubstituir ORDER BY IC_ID DESC), (SELECT TOP 1 REV_ID FROM TB_REVISAO WHERE CONT_ID = idContratoSubstituir ORDER BY REV_ID DESC),
        1, GETDATE(), GETDATE(), N'gcont.admin', N'gcont.admin', 1.00000000, 1.00000000, 0.00000000, 2.56000000, 0.00000000, 2.56000000, 2.56000000, null, 1000000, N'1',
        N'Caneta esferográfica personalizável com impressão monocromática, corpo em plástico na cor branca, gripe emborrachado na mesma cor do clipe, medindo aproximadamente 13 cm, escrita azul.',
        N'81911', N'Unidade', null, N'N', N'N', N'ITEM_NAO_REAJUSTADO', idContratoSubstituir, null, null, null, 0.00000000, N'S',
        N'33903299', N'FIXO', N'N', null, null, null);


INSERT INTO DB_CONTRATOS.dbo.AUD_TB_PARCELA_CONTRATO (PC_ID, PC_ID_ORIGEM, REV_ID, TIPO_REVISAO, AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, PC_TIPO, PC_NUM_PARCELA,
                                                      PC_QTD_DIAS_APOS_MED, PC_VALOR, PC_DT_VENC, CONT_ID, MD_ID, PC_VALOR_ANTERIOR_ALTERACAO, PC_VALOR_ALTERACAO,
                                                      PC_MOTIVO_NAO_SOLICITACAO, PC_USUARIO_NAO_SOLICITACAO, PC_DATA_NAO_SOLICITACAO)
VALUES ((SELECT TOP 1 PC_ID FROM TB_PARCELA_CONTRATO WHERE CONT_ID = idContratoSubstituir ORDER BY PC_ID DESC), (SELECT TOP 1 PC_ID_ORIGEM FROM TB_PARCELA_CONTRATO WHERE CONT_ID = idContratoSubstituir ORDER BY PC_ID DESC),
        (SELECT TOP 1 REV_ID FROM TB_REVISAO WHERE CONT_ID = idContratoSubstituir ORDER BY REV_ID DESC), 1, N'2022-12-05 09:48:56.323', N'2022-12-05 10:46:32.453',
        N'gcont.admin', N'gcont.admin', N'ITEM', 1, 0, 0.00000000, N'2024-12-26 00:00:00.000', idContratoSubstituir,
        (SELECT TOP 1 MD_ID FROM TB_MEDICAO WHERE CONT_ID = idContratoSubstituir ORDER BY MD_ID DESC), null, null, null, null, null);


INSERT INTO DB_CONTRATOS.dbo.AUD_TB_CONT (CONT_ID, REV_ID, TIPO_REVISAO, AUD_DATA_CRIACAO, AUD_DATA_ULT_ALTERACAO, AUD_USUARIO_CRIACAO, AUD_USUARIO_ULT_ALTERACAO, CONT_NUM_CONTRATO_DOC,
                                          CONT_NUM_CONTRATO_SEQ, CONT_ANO_CONTRATO, CONT_NUM_PROC_AUXILIAR, CONT_NUM_PROC_LICITATORIO, CONT_NOME_ULTIMO_GESTOR, CONT_NOME_ULTIMO_FISCAL,
                                          CONT_VAL_INICIAL_CONTRATO, CONT_VAL_ATUAL_CONTRATO, CONT_TOTAL_ACRESCIMO, CONT_TOTAL_SUPRESSAO, CONT_TOTAL_PERC_ACRESCIMO, CONT_TOTAL_PERC_SUPRESSAO,
                                          CONT_SITUACAO_CONTRATO, CONT_PUBLICADO, CONT_OBJETO, CONT_FORN_CNPJ, CONT_FORN_RAZAO_SOCIAL, CONT_FORN_TELEFONE, CONT_FORN_RESPONSAVEIS,
                                          WFK_CONT_ORGAO, WFK_CONT_AC, WFK_CONT_MU, WFK_CONT_ORD, FK_CONT_TDOC, FK_CONT_TAQ, CONT_MANUAL, CONT_NUM_PROC_UTILIZACAO, CONT_EXERCICIO,
                                          WFK_CONT_ORG_COD_GESTAO, CONT_NUM_ATA_EDITAL, CONT_RENOVACAO, FK_CONT_ORIGINAL, CONT_NUM_LAUDO, CONT_DATA_INI_VIGENCIA,
                                          CONT_DATA_FIM_VIGENCIA, CONT_DATA_ASSINATURA, CONT_DATA_PUBLICACAO, CONT_LAUDO, CONT_NUM_GERADO_AUTO, CONT_FORN_TIPO_PESSOA,
                                          CONT_TOTAL_DURACAO_DIAS, CONT_SITUACAO_EXECUCAO, CONT_REPROGRAMACAO, CONT_ID_ALT_ORIGEM_RENOVACAO, CONT_SEM_VALOR, CONT_REPLANEJAMENTO,
                                          CONT_BLOQUEADO_ADMIN, CONT_AC_SUBROGACAO, CONT_AC_ID_ORGAO_CONTRATANTE, CONT_AC_ID_ORD_DESP, CONT_JUSTIFICATIVA_NAO_IMPORT,
                                          CONT_USUARIO_JUSTIF_NAO_IMPORT, CONT_DATA_JUSTIF_NAO_IMPORT, CONT_AC_EXERCICIO, CONT_LOCALIZACAO_OBRA)
SELECT idContratoSubstituir, (SELECT TOP 1 REV_ID FROM TB_REVISAO WHERE CONT_ID = idContratoSubstituir ORDER BY REV_ID DESC),
       1, GETDATE(), GETDATE(), N'gcont.admin', N'gcont.admin', CONT_NUM_CONTRATO_DOC, CONT_NUM_CONTRATO_SEQ, CONT_ANO_CONTRATO, CONT_NUM_PROC_AUXILIAR, CONT_NUM_PROC_LICITATORIO, CONT_NOME_ULTIMO_GESTOR,
       CONT_NOME_ULTIMO_FISCAL, CONT_VAL_INICIAL_CONTRATO, CONT_VAL_ATUAL_CONTRATO, CONT_TOTAL_ACRESCIMO, CONT_TOTAL_SUPRESSAO, CONT_TOTAL_PERC_ACRESCIMO, CONT_TOTAL_PERC_SUPRESSAO,
       CONT_SITUACAO_CONTRATO, CONT_PUBLICADO, CONT_OBJETO, CONT_FORN_CNPJ, CONT_FORN_RAZAO_SOCIAL, CONT_FORN_TELEFONE, CONT_FORN_RESPONSAVEIS,
       WFK_CONT_ORGAO, WFK_CONT_AC, WFK_CONT_MU, WFK_CONT_ORD,
       (SELECT TOP 1 FK_CONT_TDOC FROM TB_CONT WHERE CONT_ID = idContratoSubstituir), -- NO SCRIPT ESTA NULL
       (SELECT TOP 1 FK_CONT_TAQ FROM TB_CONT WHERE CONT_ID = idContratoSubstituir), -- NO SCRIPT ESTA NULL
       CONT_MANUAL, CONT_NUM_PROC_UTILIZACAO, CONT_EXERCICIO, WFK_CONT_ORG_COD_GESTAO, CONT_NUM_ATA_EDITAL, CONT_RENOVACAO, FK_CONT_ORIGINAL, CONT_NUM_LAUDO, CONT_DATA_INI_VIGENCIA,
       CONT_DATA_FIM_VIGENCIA, CONT_DATA_ASSINATURA, CONT_DATA_PUBLICACAO, CONT_LAUDO, CONT_NUM_GERADO_AUTO, CONT_FORN_TIPO_PESSOA,
       CONT_TOTAL_DURACAO_DIAS, CONT_SITUACAO_EXECUCAO, CONT_REPROGRAMACAO, CONT_ID_ALT_ORIGEM_RENOVACAO, CONT_SEM_VALOR, CONT_REPLANEJAMENTO,
       CONT_BLOQUEADO_ADMIN, CONT_AC_SUBROGACAO, CONT_AC_ID_ORGAO_CONTRATANTE, CONT_AC_ID_ORD_DESP, CONT_JUSTIFICATIVA_NAO_IMPORT,
       CONT_USUARIO_JUSTIF_NAO_IMPORT, CONT_DATA_JUSTIF_NAO_IMPORT, CONT_AC_EXERCICIO, CONT_LOCALIZACAO_OBRA
FROM TB_CONT
WHERE CONT_ID = idContratoSubstituir;



